pipeline {
    agent any
    stages {

        stage('Build') {
            steps {
                echo 'Building the application...'
            }
        }

        stage('Desenvolvimento') {
            steps {
                input message: 'Confirmar deploy em DESENVOLVIMENTO?', ok: 'OK'
                sh 'mkdir -p /tmp/Desenvolvimento'
                echo 'Deploy em Desenvolvimento...'
            }
        }

        stage('Homologação') {
            steps {
                input message: 'Confirmar deploy em HOMOLOGAÇÃO?', ok: 'OK'
                sh 'mkdir -p /tmp/Homologacao'
                echo 'Deploy em Homologação...'
            }
        }

        stage('Produção') {
            steps {
                input message: 'Confirmar deploy em PRODUÇÃO?', ok: 'OK'
                sh 'mkdir -p /tmp/Producao'
                echo 'Deploy em Produção...'
            }
        }
    }
}
