pipeline {
    agent any

    environment {
        SONAR_SCANNER = tool 'sonar-scanner'
        SONARQUBE_ENV = 'SonarQube'
    }

    stages {
                
        stage('SonarQube - Backend Node.js') {
            steps {
                dir('scripts') {
                    withSonarQubeEnv("${SONARQUBE_ENV}") {
                        sh """
                        ${SONAR_SCANNER} \
                        -Dproject.settings=sonar-project.properties
                        """
                    }
                }
            }
        }

        stage('Build') {
            steps {
                echo 'Building the application...'
            }
        }        

        stage('Desenvolvimento') {
            steps {
                input message: 'Confirmar deploy em DESENVOLVIMENTO?', ok: 'OK'
                sh 'mkdir -p /tmp/Desenvolvimento'
                echo 'Deploy em Desenvolvimento...'
            }
        }

        stage('Homologação') {
            steps {
                input message: 'Confirmar deploy em HOMOLOGAÇÃO?', ok: 'OK'
                sh 'mkdir -p /tmp/Homologacao'
                echo 'Deploy em Homologação...'
            }
        }

        stage('Produção') {
            steps {
                input message: 'Confirmar deploy em PRODUÇÃO?', ok: 'OK'
                sh 'mkdir -p /tmp/Producao'
                echo 'Deploy em Produção...'
            }
        }
    }
}
